// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	SysDict          *sysDict
	SysDictType      *sysDictType
	SysMenu          *sysMenu
	SysTracker       *sysTracker
	SysUser          *sysUser
	SysUserAuth      *sysUserAuth
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	SysDict = &Q.SysDict
	SysDictType = &Q.SysDictType
	SysMenu = &Q.SysMenu
	SysTracker = &Q.SysTracker
	SysUser = &Q.SysUser
	SysUserAuth = &Q.SysUserAuth
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		SysDict:          newSysDict(db, opts...),
		SysDictType:      newSysDictType(db, opts...),
		SysMenu:          newSysMenu(db, opts...),
		SysTracker:       newSysTracker(db, opts...),
		SysUser:          newSysUser(db, opts...),
		SysUserAuth:      newSysUserAuth(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	SysDict          sysDict
	SysDictType      sysDictType
	SysMenu          sysMenu
	SysTracker       sysTracker
	SysUser          sysUser
	SysUserAuth      sysUserAuth
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		SysDict:          q.SysDict.clone(db),
		SysDictType:      q.SysDictType.clone(db),
		SysMenu:          q.SysMenu.clone(db),
		SysTracker:       q.SysTracker.clone(db),
		SysUser:          q.SysUser.clone(db),
		SysUserAuth:      q.SysUserAuth.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		SysDict:          q.SysDict.replaceDB(db),
		SysDictType:      q.SysDictType.replaceDB(db),
		SysMenu:          q.SysMenu.replaceDB(db),
		SysTracker:       q.SysTracker.replaceDB(db),
		SysUser:          q.SysUser.replaceDB(db),
		SysUserAuth:      q.SysUserAuth.replaceDB(db),
	}
}

type queryCtx struct {
	SysDict          ISysDictDo
	SysDictType      ISysDictTypeDo
	SysMenu          ISysMenuDo
	SysTracker       ISysTrackerDo
	SysUser          ISysUserDo
	SysUserAuth      ISysUserAuthDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SysDict:          q.SysDict.WithContext(ctx),
		SysDictType:      q.SysDictType.WithContext(ctx),
		SysMenu:          q.SysMenu.WithContext(ctx),
		SysTracker:       q.SysTracker.WithContext(ctx),
		SysUser:          q.SysUser.WithContext(ctx),
		SysUserAuth:      q.SysUserAuth.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
