// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/7as0nch/backend/models/generator/model"
)

func newOpslabsAttempt(db *gorm.DB, opts ...gen.DOOption) opslabsAttempt {
	_opslabsAttempt := opslabsAttempt{}

	_opslabsAttempt.opslabsAttemptDo.UseDB(db, opts...)
	_opslabsAttempt.opslabsAttemptDo.UseModel(&model.OpslabsAttempt{})

	tableName := _opslabsAttempt.opslabsAttemptDo.TableName()
	_opslabsAttempt.ALL = field.NewAsterisk(tableName)
	_opslabsAttempt.ID = field.NewInt64(tableName, "id")
	_opslabsAttempt.CreatedAt = field.NewField(tableName, "created_at")
	_opslabsAttempt.CreatedBy = field.NewInt64(tableName, "created_by")
	_opslabsAttempt.UpdatedAt = field.NewField(tableName, "updated_at")
	_opslabsAttempt.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_opslabsAttempt.IsDeleted = field.NewUint(tableName, "is_deleted")
	_opslabsAttempt.DeletedAt = field.NewField(tableName, "deleted_at")
	_opslabsAttempt.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_opslabsAttempt.UserID = field.NewInt64(tableName, "user_id")
	_opslabsAttempt.ScenarioSlug = field.NewString(tableName, "scenario_slug")
	_opslabsAttempt.ContainerID = field.NewString(tableName, "container_id")
	_opslabsAttempt.HostPort = field.NewInt(tableName, "host_port")
	_opslabsAttempt.Status = field.NewString(tableName, "status")
	_opslabsAttempt.StartedAt = field.NewTime(tableName, "started_at")
	_opslabsAttempt.LastActiveAt = field.NewTime(tableName, "last_active_at")
	_opslabsAttempt.FinishedAt = field.NewTime(tableName, "finished_at")
	_opslabsAttempt.DurationMS = field.NewInt64(tableName, "duration_ms")
	_opslabsAttempt.CheckCount = field.NewInt(tableName, "check_count")

	_opslabsAttempt.fillFieldMap()

	return _opslabsAttempt
}

type opslabsAttempt struct {
	opslabsAttemptDo

	ALL          field.Asterisk
	ID           field.Int64
	CreatedAt    field.Field
	CreatedBy    field.Int64
	UpdatedAt    field.Field
	UpdatedBy    field.Int64
	IsDeleted    field.Uint
	DeletedAt    field.Field
	DeletedBy    field.Int64
	UserID       field.Int64
	ScenarioSlug field.String
	ContainerID  field.String
	HostPort     field.Int
	Status       field.String
	StartedAt    field.Time
	LastActiveAt field.Time
	FinishedAt   field.Time
	DurationMS   field.Int64
	CheckCount   field.Int

	fieldMap map[string]field.Expr
}

func (o opslabsAttempt) Table(newTableName string) *opslabsAttempt {
	o.opslabsAttemptDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o opslabsAttempt) As(alias string) *opslabsAttempt {
	o.opslabsAttemptDo.DO = *(o.opslabsAttemptDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *opslabsAttempt) updateTableName(table string) *opslabsAttempt {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.CreatedAt = field.NewField(table, "created_at")
	o.CreatedBy = field.NewInt64(table, "created_by")
	o.UpdatedAt = field.NewField(table, "updated_at")
	o.UpdatedBy = field.NewInt64(table, "updated_by")
	o.IsDeleted = field.NewUint(table, "is_deleted")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.DeletedBy = field.NewInt64(table, "deleted_by")
	o.UserID = field.NewInt64(table, "user_id")
	o.ScenarioSlug = field.NewString(table, "scenario_slug")
	o.ContainerID = field.NewString(table, "container_id")
	o.HostPort = field.NewInt(table, "host_port")
	o.Status = field.NewString(table, "status")
	o.StartedAt = field.NewTime(table, "started_at")
	o.LastActiveAt = field.NewTime(table, "last_active_at")
	o.FinishedAt = field.NewTime(table, "finished_at")
	o.DurationMS = field.NewInt64(table, "duration_ms")
	o.CheckCount = field.NewInt(table, "check_count")

	o.fillFieldMap()

	return o
}

func (o *opslabsAttempt) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *opslabsAttempt) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 18)
	o.fieldMap["id"] = o.ID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["created_by"] = o.CreatedBy
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["updated_by"] = o.UpdatedBy
	o.fieldMap["is_deleted"] = o.IsDeleted
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["deleted_by"] = o.DeletedBy
	o.fieldMap["user_id"] = o.UserID
	o.fieldMap["scenario_slug"] = o.ScenarioSlug
	o.fieldMap["container_id"] = o.ContainerID
	o.fieldMap["host_port"] = o.HostPort
	o.fieldMap["status"] = o.Status
	o.fieldMap["started_at"] = o.StartedAt
	o.fieldMap["last_active_at"] = o.LastActiveAt
	o.fieldMap["finished_at"] = o.FinishedAt
	o.fieldMap["duration_ms"] = o.DurationMS
	o.fieldMap["check_count"] = o.CheckCount
}

func (o opslabsAttempt) clone(db *gorm.DB) opslabsAttempt {
	o.opslabsAttemptDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o opslabsAttempt) replaceDB(db *gorm.DB) opslabsAttempt {
	o.opslabsAttemptDo.ReplaceDB(db)
	return o
}

type opslabsAttemptDo struct{ gen.DO }

type IOpslabsAttemptDo interface {
	gen.SubQuery
	Debug() IOpslabsAttemptDo
	WithContext(ctx context.Context) IOpslabsAttemptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOpslabsAttemptDo
	WriteDB() IOpslabsAttemptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOpslabsAttemptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOpslabsAttemptDo
	Not(conds ...gen.Condition) IOpslabsAttemptDo
	Or(conds ...gen.Condition) IOpslabsAttemptDo
	Select(conds ...field.Expr) IOpslabsAttemptDo
	Where(conds ...gen.Condition) IOpslabsAttemptDo
	Order(conds ...field.Expr) IOpslabsAttemptDo
	Distinct(cols ...field.Expr) IOpslabsAttemptDo
	Omit(cols ...field.Expr) IOpslabsAttemptDo
	Join(table schema.Tabler, on ...field.Expr) IOpslabsAttemptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOpslabsAttemptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOpslabsAttemptDo
	Group(cols ...field.Expr) IOpslabsAttemptDo
	Having(conds ...gen.Condition) IOpslabsAttemptDo
	Limit(limit int) IOpslabsAttemptDo
	Offset(offset int) IOpslabsAttemptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOpslabsAttemptDo
	Unscoped() IOpslabsAttemptDo
	Create(values ...*model.OpslabsAttempt) error
	CreateInBatches(values []*model.OpslabsAttempt, batchSize int) error
	Save(values ...*model.OpslabsAttempt) error
	First() (*model.OpslabsAttempt, error)
	Take() (*model.OpslabsAttempt, error)
	Last() (*model.OpslabsAttempt, error)
	Find() ([]*model.OpslabsAttempt, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OpslabsAttempt, err error)
	FindInBatches(result *[]*model.OpslabsAttempt, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OpslabsAttempt) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOpslabsAttemptDo
	Assign(attrs ...field.AssignExpr) IOpslabsAttemptDo
	Joins(fields ...field.RelationField) IOpslabsAttemptDo
	Preload(fields ...field.RelationField) IOpslabsAttemptDo
	FirstOrInit() (*model.OpslabsAttempt, error)
	FirstOrCreate() (*model.OpslabsAttempt, error)
	FindByPage(offset int, limit int) (result []*model.OpslabsAttempt, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOpslabsAttemptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o opslabsAttemptDo) Debug() IOpslabsAttemptDo {
	return o.withDO(o.DO.Debug())
}

func (o opslabsAttemptDo) WithContext(ctx context.Context) IOpslabsAttemptDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o opslabsAttemptDo) ReadDB() IOpslabsAttemptDo {
	return o.Clauses(dbresolver.Read)
}

func (o opslabsAttemptDo) WriteDB() IOpslabsAttemptDo {
	return o.Clauses(dbresolver.Write)
}

func (o opslabsAttemptDo) Session(config *gorm.Session) IOpslabsAttemptDo {
	return o.withDO(o.DO.Session(config))
}

func (o opslabsAttemptDo) Clauses(conds ...clause.Expression) IOpslabsAttemptDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o opslabsAttemptDo) Returning(value interface{}, columns ...string) IOpslabsAttemptDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o opslabsAttemptDo) Not(conds ...gen.Condition) IOpslabsAttemptDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o opslabsAttemptDo) Or(conds ...gen.Condition) IOpslabsAttemptDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o opslabsAttemptDo) Select(conds ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o opslabsAttemptDo) Where(conds ...gen.Condition) IOpslabsAttemptDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o opslabsAttemptDo) Order(conds ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o opslabsAttemptDo) Distinct(cols ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o opslabsAttemptDo) Omit(cols ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o opslabsAttemptDo) Join(table schema.Tabler, on ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o opslabsAttemptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o opslabsAttemptDo) RightJoin(table schema.Tabler, on ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o opslabsAttemptDo) Group(cols ...field.Expr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o opslabsAttemptDo) Having(conds ...gen.Condition) IOpslabsAttemptDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o opslabsAttemptDo) Limit(limit int) IOpslabsAttemptDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o opslabsAttemptDo) Offset(offset int) IOpslabsAttemptDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o opslabsAttemptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOpslabsAttemptDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o opslabsAttemptDo) Unscoped() IOpslabsAttemptDo {
	return o.withDO(o.DO.Unscoped())
}

func (o opslabsAttemptDo) Create(values ...*model.OpslabsAttempt) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o opslabsAttemptDo) CreateInBatches(values []*model.OpslabsAttempt, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o opslabsAttemptDo) Save(values ...*model.OpslabsAttempt) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o opslabsAttemptDo) First() (*model.OpslabsAttempt, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OpslabsAttempt), nil
	}
}

func (o opslabsAttemptDo) Take() (*model.OpslabsAttempt, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OpslabsAttempt), nil
	}
}

func (o opslabsAttemptDo) Last() (*model.OpslabsAttempt, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OpslabsAttempt), nil
	}
}

func (o opslabsAttemptDo) Find() ([]*model.OpslabsAttempt, error) {
	result, err := o.DO.Find()
	return result.([]*model.OpslabsAttempt), err
}

func (o opslabsAttemptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OpslabsAttempt, err error) {
	buf := make([]*model.OpslabsAttempt, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o opslabsAttemptDo) FindInBatches(result *[]*model.OpslabsAttempt, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o opslabsAttemptDo) Attrs(attrs ...field.AssignExpr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o opslabsAttemptDo) Assign(attrs ...field.AssignExpr) IOpslabsAttemptDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o opslabsAttemptDo) Joins(fields ...field.RelationField) IOpslabsAttemptDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o opslabsAttemptDo) Preload(fields ...field.RelationField) IOpslabsAttemptDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o opslabsAttemptDo) FirstOrInit() (*model.OpslabsAttempt, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OpslabsAttempt), nil
	}
}

func (o opslabsAttemptDo) FirstOrCreate() (*model.OpslabsAttempt, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OpslabsAttempt), nil
	}
}

func (o opslabsAttemptDo) FindByPage(offset int, limit int) (result []*model.OpslabsAttempt, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o opslabsAttemptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o opslabsAttemptDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o opslabsAttemptDo) Delete(models ...*model.OpslabsAttempt) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *opslabsAttemptDo) withDO(do gen.Dao) *opslabsAttemptDo {
	o.DO = *do.(*gen.DO)
	return o
}
