// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/example/aichat/backend/models/generator/model"
)

func newSysUserAuth(db *gorm.DB, opts ...gen.DOOption) sysUserAuth {
	_sysUserAuth := sysUserAuth{}

	_sysUserAuth.sysUserAuthDo.UseDB(db, opts...)
	_sysUserAuth.sysUserAuthDo.UseModel(&model.SysUserAuth{})

	tableName := _sysUserAuth.sysUserAuthDo.TableName()
	_sysUserAuth.ALL = field.NewAsterisk(tableName)
	_sysUserAuth.ID = field.NewInt64(tableName, "id")
	_sysUserAuth.CreatedAt = field.NewField(tableName, "created_at")
	_sysUserAuth.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysUserAuth.UpdatedAt = field.NewField(tableName, "updated_at")
	_sysUserAuth.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_sysUserAuth.IsDeleted = field.NewUint(tableName, "is_deleted")
	_sysUserAuth.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysUserAuth.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_sysUserAuth.UserID = field.NewInt64(tableName, "user_id")
	_sysUserAuth.AuthType = field.NewInt(tableName, "auth_type")
	_sysUserAuth.Identifier = field.NewString(tableName, "identifier")
	_sysUserAuth.Secret = field.NewString(tableName, "secret")

	_sysUserAuth.fillFieldMap()

	return _sysUserAuth
}

type sysUserAuth struct {
	sysUserAuthDo

	ALL        field.Asterisk
	ID         field.Int64
	CreatedAt  field.Field
	CreatedBy  field.Int64
	UpdatedAt  field.Field
	UpdatedBy  field.Int64
	IsDeleted  field.Uint
	DeletedAt  field.Field
	DeletedBy  field.Int64
	UserID     field.Int64
	AuthType   field.Int
	Identifier field.String
	Secret     field.String

	fieldMap map[string]field.Expr
}

func (s sysUserAuth) Table(newTableName string) *sysUserAuth {
	s.sysUserAuthDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysUserAuth) As(alias string) *sysUserAuth {
	s.sysUserAuthDo.DO = *(s.sysUserAuthDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysUserAuth) updateTableName(table string) *sysUserAuth {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewField(table, "created_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.UpdatedBy = field.NewInt64(table, "updated_by")
	s.IsDeleted = field.NewUint(table, "is_deleted")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.DeletedBy = field.NewInt64(table, "deleted_by")
	s.UserID = field.NewInt64(table, "user_id")
	s.AuthType = field.NewInt(table, "auth_type")
	s.Identifier = field.NewString(table, "identifier")
	s.Secret = field.NewString(table, "secret")

	s.fillFieldMap()

	return s
}

func (s *sysUserAuth) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysUserAuth) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["is_deleted"] = s.IsDeleted
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["auth_type"] = s.AuthType
	s.fieldMap["identifier"] = s.Identifier
	s.fieldMap["secret"] = s.Secret
}

func (s sysUserAuth) clone(db *gorm.DB) sysUserAuth {
	s.sysUserAuthDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysUserAuth) replaceDB(db *gorm.DB) sysUserAuth {
	s.sysUserAuthDo.ReplaceDB(db)
	return s
}

type sysUserAuthDo struct{ gen.DO }

type ISysUserAuthDo interface {
	gen.SubQuery
	Debug() ISysUserAuthDo
	WithContext(ctx context.Context) ISysUserAuthDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysUserAuthDo
	WriteDB() ISysUserAuthDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysUserAuthDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysUserAuthDo
	Not(conds ...gen.Condition) ISysUserAuthDo
	Or(conds ...gen.Condition) ISysUserAuthDo
	Select(conds ...field.Expr) ISysUserAuthDo
	Where(conds ...gen.Condition) ISysUserAuthDo
	Order(conds ...field.Expr) ISysUserAuthDo
	Distinct(cols ...field.Expr) ISysUserAuthDo
	Omit(cols ...field.Expr) ISysUserAuthDo
	Join(table schema.Tabler, on ...field.Expr) ISysUserAuthDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserAuthDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysUserAuthDo
	Group(cols ...field.Expr) ISysUserAuthDo
	Having(conds ...gen.Condition) ISysUserAuthDo
	Limit(limit int) ISysUserAuthDo
	Offset(offset int) ISysUserAuthDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserAuthDo
	Unscoped() ISysUserAuthDo
	Create(values ...*model.SysUserAuth) error
	CreateInBatches(values []*model.SysUserAuth, batchSize int) error
	Save(values ...*model.SysUserAuth) error
	First() (*model.SysUserAuth, error)
	Take() (*model.SysUserAuth, error)
	Last() (*model.SysUserAuth, error)
	Find() ([]*model.SysUserAuth, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserAuth, err error)
	FindInBatches(result *[]*model.SysUserAuth, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysUserAuth) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysUserAuthDo
	Assign(attrs ...field.AssignExpr) ISysUserAuthDo
	Joins(fields ...field.RelationField) ISysUserAuthDo
	Preload(fields ...field.RelationField) ISysUserAuthDo
	FirstOrInit() (*model.SysUserAuth, error)
	FirstOrCreate() (*model.SysUserAuth, error)
	FindByPage(offset int, limit int) (result []*model.SysUserAuth, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysUserAuthDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysUserAuthDo) Debug() ISysUserAuthDo {
	return s.withDO(s.DO.Debug())
}

func (s sysUserAuthDo) WithContext(ctx context.Context) ISysUserAuthDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysUserAuthDo) ReadDB() ISysUserAuthDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysUserAuthDo) WriteDB() ISysUserAuthDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysUserAuthDo) Session(config *gorm.Session) ISysUserAuthDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysUserAuthDo) Clauses(conds ...clause.Expression) ISysUserAuthDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysUserAuthDo) Returning(value interface{}, columns ...string) ISysUserAuthDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysUserAuthDo) Not(conds ...gen.Condition) ISysUserAuthDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysUserAuthDo) Or(conds ...gen.Condition) ISysUserAuthDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysUserAuthDo) Select(conds ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysUserAuthDo) Where(conds ...gen.Condition) ISysUserAuthDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysUserAuthDo) Order(conds ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysUserAuthDo) Distinct(cols ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysUserAuthDo) Omit(cols ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysUserAuthDo) Join(table schema.Tabler, on ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysUserAuthDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysUserAuthDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysUserAuthDo) Group(cols ...field.Expr) ISysUserAuthDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysUserAuthDo) Having(conds ...gen.Condition) ISysUserAuthDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysUserAuthDo) Limit(limit int) ISysUserAuthDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysUserAuthDo) Offset(offset int) ISysUserAuthDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysUserAuthDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysUserAuthDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysUserAuthDo) Unscoped() ISysUserAuthDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysUserAuthDo) Create(values ...*model.SysUserAuth) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysUserAuthDo) CreateInBatches(values []*model.SysUserAuth, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysUserAuthDo) Save(values ...*model.SysUserAuth) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysUserAuthDo) First() (*model.SysUserAuth, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) Take() (*model.SysUserAuth, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) Last() (*model.SysUserAuth, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) Find() ([]*model.SysUserAuth, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysUserAuth), err
}

func (s sysUserAuthDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysUserAuth, err error) {
	buf := make([]*model.SysUserAuth, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysUserAuthDo) FindInBatches(result *[]*model.SysUserAuth, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysUserAuthDo) Attrs(attrs ...field.AssignExpr) ISysUserAuthDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysUserAuthDo) Assign(attrs ...field.AssignExpr) ISysUserAuthDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysUserAuthDo) Joins(fields ...field.RelationField) ISysUserAuthDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysUserAuthDo) Preload(fields ...field.RelationField) ISysUserAuthDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysUserAuthDo) FirstOrInit() (*model.SysUserAuth, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) FirstOrCreate() (*model.SysUserAuth, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysUserAuth), nil
	}
}

func (s sysUserAuthDo) FindByPage(offset int, limit int) (result []*model.SysUserAuth, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysUserAuthDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysUserAuthDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysUserAuthDo) Delete(models ...*model.SysUserAuth) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysUserAuthDo) withDO(do gen.Dao) *sysUserAuthDo {
	s.DO = *do.(*gen.DO)
	return s
}
