// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/example/aichat/backend/models/generator/model"
)

func newSysTracker(db *gorm.DB, opts ...gen.DOOption) sysTracker {
	_sysTracker := sysTracker{}

	_sysTracker.sysTrackerDo.UseDB(db, opts...)
	_sysTracker.sysTrackerDo.UseModel(&model.SysTracker{})

	tableName := _sysTracker.sysTrackerDo.TableName()
	_sysTracker.ALL = field.NewAsterisk(tableName)
	_sysTracker.ID = field.NewInt64(tableName, "id")
	_sysTracker.CreatedAt = field.NewField(tableName, "created_at")
	_sysTracker.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysTracker.UpdatedAt = field.NewField(tableName, "updated_at")
	_sysTracker.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_sysTracker.IsDeleted = field.NewUint(tableName, "is_deleted")
	_sysTracker.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysTracker.DeletedBy = field.NewInt64(tableName, "deleted_by")
	_sysTracker.AppId = field.NewString(tableName, "app_id")
	_sysTracker.DeviceId = field.NewString(tableName, "device_id")
	_sysTracker.UserId = field.NewInt64(tableName, "user_id")
	_sysTracker.Timestamp = field.NewString(tableName, "timestamp")
	_sysTracker.UserAgent = field.NewString(tableName, "user_agent")
	_sysTracker.PageUrl = field.NewString(tableName, "page_url")
	_sysTracker.Type = field.NewString(tableName, "type")
	_sysTracker.Data = field.NewString(tableName, "data")

	_sysTracker.fillFieldMap()

	return _sysTracker
}

type sysTracker struct {
	sysTrackerDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Field
	CreatedBy field.Int64
	UpdatedAt field.Field
	UpdatedBy field.Int64
	IsDeleted field.Uint
	DeletedAt field.Field
	DeletedBy field.Int64
	AppId     field.String
	DeviceId  field.String
	UserId    field.Int64
	Timestamp field.String
	UserAgent field.String
	PageUrl   field.String
	Type      field.String
	Data      field.String

	fieldMap map[string]field.Expr
}

func (s sysTracker) Table(newTableName string) *sysTracker {
	s.sysTrackerDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysTracker) As(alias string) *sysTracker {
	s.sysTrackerDo.DO = *(s.sysTrackerDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysTracker) updateTableName(table string) *sysTracker {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CreatedAt = field.NewField(table, "created_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.UpdatedBy = field.NewInt64(table, "updated_by")
	s.IsDeleted = field.NewUint(table, "is_deleted")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.DeletedBy = field.NewInt64(table, "deleted_by")
	s.AppId = field.NewString(table, "app_id")
	s.DeviceId = field.NewString(table, "device_id")
	s.UserId = field.NewInt64(table, "user_id")
	s.Timestamp = field.NewString(table, "timestamp")
	s.UserAgent = field.NewString(table, "user_agent")
	s.PageUrl = field.NewString(table, "page_url")
	s.Type = field.NewString(table, "type")
	s.Data = field.NewString(table, "data")

	s.fillFieldMap()

	return s
}

func (s *sysTracker) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysTracker) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["updated_by"] = s.UpdatedBy
	s.fieldMap["is_deleted"] = s.IsDeleted
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["deleted_by"] = s.DeletedBy
	s.fieldMap["app_id"] = s.AppId
	s.fieldMap["device_id"] = s.DeviceId
	s.fieldMap["user_id"] = s.UserId
	s.fieldMap["timestamp"] = s.Timestamp
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["page_url"] = s.PageUrl
	s.fieldMap["type"] = s.Type
	s.fieldMap["data"] = s.Data
}

func (s sysTracker) clone(db *gorm.DB) sysTracker {
	s.sysTrackerDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysTracker) replaceDB(db *gorm.DB) sysTracker {
	s.sysTrackerDo.ReplaceDB(db)
	return s
}

type sysTrackerDo struct{ gen.DO }

type ISysTrackerDo interface {
	gen.SubQuery
	Debug() ISysTrackerDo
	WithContext(ctx context.Context) ISysTrackerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysTrackerDo
	WriteDB() ISysTrackerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysTrackerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysTrackerDo
	Not(conds ...gen.Condition) ISysTrackerDo
	Or(conds ...gen.Condition) ISysTrackerDo
	Select(conds ...field.Expr) ISysTrackerDo
	Where(conds ...gen.Condition) ISysTrackerDo
	Order(conds ...field.Expr) ISysTrackerDo
	Distinct(cols ...field.Expr) ISysTrackerDo
	Omit(cols ...field.Expr) ISysTrackerDo
	Join(table schema.Tabler, on ...field.Expr) ISysTrackerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysTrackerDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysTrackerDo
	Group(cols ...field.Expr) ISysTrackerDo
	Having(conds ...gen.Condition) ISysTrackerDo
	Limit(limit int) ISysTrackerDo
	Offset(offset int) ISysTrackerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysTrackerDo
	Unscoped() ISysTrackerDo
	Create(values ...*model.SysTracker) error
	CreateInBatches(values []*model.SysTracker, batchSize int) error
	Save(values ...*model.SysTracker) error
	First() (*model.SysTracker, error)
	Take() (*model.SysTracker, error)
	Last() (*model.SysTracker, error)
	Find() ([]*model.SysTracker, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysTracker, err error)
	FindInBatches(result *[]*model.SysTracker, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysTracker) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysTrackerDo
	Assign(attrs ...field.AssignExpr) ISysTrackerDo
	Joins(fields ...field.RelationField) ISysTrackerDo
	Preload(fields ...field.RelationField) ISysTrackerDo
	FirstOrInit() (*model.SysTracker, error)
	FirstOrCreate() (*model.SysTracker, error)
	FindByPage(offset int, limit int) (result []*model.SysTracker, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysTrackerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysTrackerDo) Debug() ISysTrackerDo {
	return s.withDO(s.DO.Debug())
}

func (s sysTrackerDo) WithContext(ctx context.Context) ISysTrackerDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysTrackerDo) ReadDB() ISysTrackerDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysTrackerDo) WriteDB() ISysTrackerDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysTrackerDo) Session(config *gorm.Session) ISysTrackerDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysTrackerDo) Clauses(conds ...clause.Expression) ISysTrackerDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysTrackerDo) Returning(value interface{}, columns ...string) ISysTrackerDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysTrackerDo) Not(conds ...gen.Condition) ISysTrackerDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysTrackerDo) Or(conds ...gen.Condition) ISysTrackerDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysTrackerDo) Select(conds ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysTrackerDo) Where(conds ...gen.Condition) ISysTrackerDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysTrackerDo) Order(conds ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysTrackerDo) Distinct(cols ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysTrackerDo) Omit(cols ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysTrackerDo) Join(table schema.Tabler, on ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysTrackerDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysTrackerDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysTrackerDo) Group(cols ...field.Expr) ISysTrackerDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysTrackerDo) Having(conds ...gen.Condition) ISysTrackerDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysTrackerDo) Limit(limit int) ISysTrackerDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysTrackerDo) Offset(offset int) ISysTrackerDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysTrackerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysTrackerDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysTrackerDo) Unscoped() ISysTrackerDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysTrackerDo) Create(values ...*model.SysTracker) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysTrackerDo) CreateInBatches(values []*model.SysTracker, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysTrackerDo) Save(values ...*model.SysTracker) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysTrackerDo) First() (*model.SysTracker, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTracker), nil
	}
}

func (s sysTrackerDo) Take() (*model.SysTracker, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTracker), nil
	}
}

func (s sysTrackerDo) Last() (*model.SysTracker, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTracker), nil
	}
}

func (s sysTrackerDo) Find() ([]*model.SysTracker, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysTracker), err
}

func (s sysTrackerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysTracker, err error) {
	buf := make([]*model.SysTracker, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysTrackerDo) FindInBatches(result *[]*model.SysTracker, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysTrackerDo) Attrs(attrs ...field.AssignExpr) ISysTrackerDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysTrackerDo) Assign(attrs ...field.AssignExpr) ISysTrackerDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysTrackerDo) Joins(fields ...field.RelationField) ISysTrackerDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysTrackerDo) Preload(fields ...field.RelationField) ISysTrackerDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysTrackerDo) FirstOrInit() (*model.SysTracker, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTracker), nil
	}
}

func (s sysTrackerDo) FirstOrCreate() (*model.SysTracker, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysTracker), nil
	}
}

func (s sysTrackerDo) FindByPage(offset int, limit int) (result []*model.SysTracker, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysTrackerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysTrackerDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysTrackerDo) Delete(models ...*model.SysTracker) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysTrackerDo) withDO(do gen.Dao) *sysTrackerDo {
	s.DO = *do.(*gen.DO)
	return s
}
