// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/opslabs/v1/opslabs.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Hint 提示外壳(Week 1 content 始终返回空,V2 解锁后才带内容)
type Hint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Unlocked      bool                   `protobuf:"varint,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hint) Reset() {
	*x = Hint{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hint) ProtoMessage() {}

func (x *Hint) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hint.ProtoReflect.Descriptor instead.
func (*Hint) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{0}
}

func (x *Hint) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Hint) GetUnlocked() bool {
	if x != nil {
		return x.Unlocked
	}
	return false
}

func (x *Hint) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ScenarioBrief 场景列表项(精简字段)
type ScenarioBrief struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Slug             string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary          string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Category         string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty       uint32                 `protobuf:"varint,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	EstimatedMinutes uint32                 `protobuf:"varint,6,opt,name=estimated_minutes,json=estimatedMinutes,proto3" json:"estimated_minutes,omitempty"`
	TargetPersonas   []string               `protobuf:"bytes,7,rep,name=target_personas,json=targetPersonas,proto3" json:"target_personas,omitempty"`
	TechStack        []string               `protobuf:"bytes,8,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	Tags             []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPremium        bool                   `protobuf:"varint,10,opt,name=is_premium,json=isPremium,proto3" json:"is_premium,omitempty"`
	// 执行模式:sandbox / static / wasm-linux / web-container(默认 sandbox)
	ExecutionMode string `protobuf:"bytes,11,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioBrief) Reset() {
	*x = ScenarioBrief{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioBrief) ProtoMessage() {}

func (x *ScenarioBrief) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioBrief.ProtoReflect.Descriptor instead.
func (*ScenarioBrief) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{1}
}

func (x *ScenarioBrief) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ScenarioBrief) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScenarioBrief) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ScenarioBrief) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ScenarioBrief) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *ScenarioBrief) GetEstimatedMinutes() uint32 {
	if x != nil {
		return x.EstimatedMinutes
	}
	return 0
}

func (x *ScenarioBrief) GetTargetPersonas() []string {
	if x != nil {
		return x.TargetPersonas
	}
	return nil
}

func (x *ScenarioBrief) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *ScenarioBrief) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ScenarioBrief) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *ScenarioBrief) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

// ScenarioDetail 场景详情(完整字段)
type ScenarioDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Slug             string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Summary          string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	DescriptionMd    string                 `protobuf:"bytes,5,opt,name=description_md,json=descriptionMd,proto3" json:"description_md,omitempty"`
	Category         string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty       uint32                 `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	EstimatedMinutes uint32                 `protobuf:"varint,8,opt,name=estimated_minutes,json=estimatedMinutes,proto3" json:"estimated_minutes,omitempty"`
	TargetPersonas   []string               `protobuf:"bytes,9,rep,name=target_personas,json=targetPersonas,proto3" json:"target_personas,omitempty"`
	ExperienceLevel  string                 `protobuf:"bytes,10,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"`
	TechStack        []string               `protobuf:"bytes,11,rep,name=tech_stack,json=techStack,proto3" json:"tech_stack,omitempty"`
	Skills           []string               `protobuf:"bytes,12,rep,name=skills,proto3" json:"skills,omitempty"`
	Commands         []string               `protobuf:"bytes,13,rep,name=commands,proto3" json:"commands,omitempty"`
	Tags             []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	Hints            []*Hint                `protobuf:"bytes,15,rep,name=hints,proto3" json:"hints,omitempty"`
	IsPremium        bool                   `protobuf:"varint,16,opt,name=is_premium,json=isPremium,proto3" json:"is_premium,omitempty"`
	// 执行模式:sandbox / static / wasm-linux / web-container(默认 sandbox)
	ExecutionMode string `protobuf:"bytes,17,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"`
	// bundle 资源入口:static/wasm-linux/web-container 模式下前端 Runner 的入口 URL。
	// sandbox 模式下为空。V1 由后端 embed.FS 下发,值形如 "/v1/scenarios/{slug}/bundle/index.html"
	BundleUrl     string `protobuf:"bytes,18,opt,name=bundle_url,json=bundleUrl,proto3" json:"bundle_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioDetail) Reset() {
	*x = ScenarioDetail{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioDetail) ProtoMessage() {}

func (x *ScenarioDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioDetail.ProtoReflect.Descriptor instead.
func (*ScenarioDetail) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{2}
}

func (x *ScenarioDetail) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ScenarioDetail) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ScenarioDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ScenarioDetail) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ScenarioDetail) GetDescriptionMd() string {
	if x != nil {
		return x.DescriptionMd
	}
	return ""
}

func (x *ScenarioDetail) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ScenarioDetail) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *ScenarioDetail) GetEstimatedMinutes() uint32 {
	if x != nil {
		return x.EstimatedMinutes
	}
	return 0
}

func (x *ScenarioDetail) GetTargetPersonas() []string {
	if x != nil {
		return x.TargetPersonas
	}
	return nil
}

func (x *ScenarioDetail) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *ScenarioDetail) GetTechStack() []string {
	if x != nil {
		return x.TechStack
	}
	return nil
}

func (x *ScenarioDetail) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ScenarioDetail) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ScenarioDetail) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ScenarioDetail) GetHints() []*Hint {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *ScenarioDetail) GetIsPremium() bool {
	if x != nil {
		return x.IsPremium
	}
	return false
}

func (x *ScenarioDetail) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

func (x *ScenarioDetail) GetBundleUrl() string {
	if x != nil {
		return x.BundleUrl
	}
	return ""
}

// ListScenariosRequest 场景列表查询(过滤字段 Week 2 再生效)
type ListScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Difficulty    uint32                 `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Persona       string                 `protobuf:"bytes,3,opt,name=persona,proto3" json:"persona,omitempty"`
	Tech          string                 `protobuf:"bytes,4,opt,name=tech,proto3" json:"tech,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosRequest) Reset() {
	*x = ListScenariosRequest{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosRequest) ProtoMessage() {}

func (x *ListScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListScenariosRequest) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{3}
}

func (x *ListScenariosRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListScenariosRequest) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *ListScenariosRequest) GetPersona() string {
	if x != nil {
		return x.Persona
	}
	return ""
}

func (x *ListScenariosRequest) GetTech() string {
	if x != nil {
		return x.Tech
	}
	return ""
}

func (x *ListScenariosRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListScenariosReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*ScenarioBrief       `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosReply) Reset() {
	*x = ListScenariosReply{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosReply) ProtoMessage() {}

func (x *ListScenariosReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosReply.ProtoReflect.Descriptor instead.
func (*ListScenariosReply) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{4}
}

func (x *ListScenariosReply) GetScenarios() []*ScenarioBrief {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

func (x *ListScenariosReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioRequest) Reset() {
	*x = GetScenarioRequest{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioRequest) ProtoMessage() {}

func (x *GetScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioRequest) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{5}
}

func (x *GetScenarioRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ScenarioReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *ScenarioDetail        `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScenarioReply) Reset() {
	*x = ScenarioReply{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScenarioReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScenarioReply) ProtoMessage() {}

func (x *ScenarioReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScenarioReply.ProtoReflect.Descriptor instead.
func (*ScenarioReply) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{6}
}

func (x *ScenarioReply) GetScenario() *ScenarioDetail {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type StartScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScenarioRequest) Reset() {
	*x = StartScenarioRequest{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScenarioRequest) ProtoMessage() {}

func (x *StartScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScenarioRequest.ProtoReflect.Descriptor instead.
func (*StartScenarioRequest) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{7}
}

func (x *StartScenarioRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type StartScenarioReply struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AttemptId   string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TerminalUrl string                 `protobuf:"bytes,2,opt,name=terminal_url,json=terminalUrl,proto3" json:"terminal_url,omitempty"`
	// 空闲超时时间(RFC3339)
	ExpiresAt string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// 执行模式(冗余下发,前端不必再查场景详情就能选 Runner)
	ExecutionMode string `protobuf:"bytes,4,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"`
	// bundle 资源入口(非 sandbox 模式必填)
	BundleUrl     string `protobuf:"bytes,5,opt,name=bundle_url,json=bundleUrl,proto3" json:"bundle_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScenarioReply) Reset() {
	*x = StartScenarioReply{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScenarioReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScenarioReply) ProtoMessage() {}

func (x *StartScenarioReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScenarioReply.ProtoReflect.Descriptor instead.
func (*StartScenarioReply) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{8}
}

func (x *StartScenarioReply) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *StartScenarioReply) GetTerminalUrl() string {
	if x != nil {
		return x.TerminalUrl
	}
	return ""
}

func (x *StartScenarioReply) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *StartScenarioReply) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

func (x *StartScenarioReply) GetBundleUrl() string {
	if x != nil {
		return x.BundleUrl
	}
	return ""
}

type GetAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttemptRequest) Reset() {
	*x = GetAttemptRequest{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttemptRequest) ProtoMessage() {}

func (x *GetAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttemptRequest.ProtoReflect.Descriptor instead.
func (*GetAttemptRequest) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{9}
}

func (x *GetAttemptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AttemptReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ScenarioSlug  string                 `protobuf:"bytes,2,opt,name=scenario_slug,json=scenarioSlug,proto3" json:"scenario_slug,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TerminalUrl   string                 `protobuf:"bytes,4,opt,name=terminal_url,json=terminalUrl,proto3" json:"terminal_url,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	LastActiveAt  string                 `protobuf:"bytes,6,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	ExecutionMode string                 `protobuf:"bytes,7,opt,name=execution_mode,json=executionMode,proto3" json:"execution_mode,omitempty"`
	BundleUrl     string                 `protobuf:"bytes,8,opt,name=bundle_url,json=bundleUrl,proto3" json:"bundle_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptReply) Reset() {
	*x = AttemptReply{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptReply) ProtoMessage() {}

func (x *AttemptReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptReply.ProtoReflect.Descriptor instead.
func (*AttemptReply) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{10}
}

func (x *AttemptReply) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *AttemptReply) GetScenarioSlug() string {
	if x != nil {
		return x.ScenarioSlug
	}
	return ""
}

func (x *AttemptReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AttemptReply) GetTerminalUrl() string {
	if x != nil {
		return x.TerminalUrl
	}
	return ""
}

func (x *AttemptReply) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *AttemptReply) GetLastActiveAt() string {
	if x != nil {
		return x.LastActiveAt
	}
	return ""
}

func (x *AttemptReply) GetExecutionMode() string {
	if x != nil {
		return x.ExecutionMode
	}
	return ""
}

func (x *AttemptReply) GetBundleUrl() string {
	if x != nil {
		return x.BundleUrl
	}
	return ""
}

// ClientCheckResult 前端/wasm runner 自带的判题结果
// 非 sandbox 模式下由前端跑完后上报;sandbox 模式忽略此字段(后端 docker exec 跑 check.sh)
type ClientCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passed        bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientCheckResult) Reset() {
	*x = ClientCheckResult{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCheckResult) ProtoMessage() {}

func (x *ClientCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCheckResult.ProtoReflect.Descriptor instead.
func (*ClientCheckResult) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{11}
}

func (x *ClientCheckResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ClientCheckResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ClientCheckResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ClientCheckResult) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type CheckAttemptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 仅非 sandbox 模式使用:前端 Runner 自己跑完判题后把结果带上来
	ClientResult  *ClientCheckResult `protobuf:"bytes,2,opt,name=client_result,json=clientResult,proto3" json:"client_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAttemptRequest) Reset() {
	*x = CheckAttemptRequest{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptRequest) ProtoMessage() {}

func (x *CheckAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptRequest.ProtoReflect.Descriptor instead.
func (*CheckAttemptRequest) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{12}
}

func (x *CheckAttemptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckAttemptRequest) GetClientResult() *ClientCheckResult {
	if x != nil {
		return x.ClientResult
	}
	return nil
}

type CheckAttemptReply struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Passed  bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 仅通关时返回
	DurationSeconds uint32 `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	CheckCount      uint32 `protobuf:"varint,4,opt,name=check_count,json=checkCount,proto3" json:"check_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckAttemptReply) Reset() {
	*x = CheckAttemptReply{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAttemptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptReply) ProtoMessage() {}

func (x *CheckAttemptReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptReply.ProtoReflect.Descriptor instead.
func (*CheckAttemptReply) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{13}
}

func (x *CheckAttemptReply) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *CheckAttemptReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckAttemptReply) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *CheckAttemptReply) GetCheckCount() uint32 {
	if x != nil {
		return x.CheckCount
	}
	return 0
}

type TerminateAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateAttemptRequest) Reset() {
	*x = TerminateAttemptRequest{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateAttemptRequest) ProtoMessage() {}

func (x *TerminateAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateAttemptRequest.ProtoReflect.Descriptor instead.
func (*TerminateAttemptRequest) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{14}
}

func (x *TerminateAttemptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TerminateAttemptReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateAttemptReply) Reset() {
	*x = TerminateAttemptReply{}
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateAttemptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateAttemptReply) ProtoMessage() {}

func (x *TerminateAttemptReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_opslabs_v1_opslabs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateAttemptReply.ProtoReflect.Descriptor instead.
func (*TerminateAttemptReply) Descriptor() ([]byte, []int) {
	return file_api_opslabs_v1_opslabs_proto_rawDescGZIP(), []int{15}
}

func (x *TerminateAttemptReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_opslabs_v1_opslabs_proto protoreflect.FileDescriptor

const file_api_opslabs_v1_opslabs_proto_rawDesc = "" +
	"\n" +
	"\x1capi/opslabs/v1/opslabs.proto\x12\n" +
	"opslabs.v1\x1a\x1cgoogle/api/annotations.proto\"R\n" +
	"\x04Hint\x12\x14\n" +
	"\x05level\x18\x01 \x01(\rR\x05level\x12\x1a\n" +
	"\bunlocked\x18\x02 \x01(\bR\bunlocked\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xde\x02\n" +
	"\rScenarioBrief\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\rR\n" +
	"difficulty\x12+\n" +
	"\x11estimated_minutes\x18\x06 \x01(\rR\x10estimatedMinutes\x12'\n" +
	"\x0ftarget_personas\x18\a \x03(\tR\x0etargetPersonas\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\b \x03(\tR\ttechStack\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"is_premium\x18\n" +
	" \x01(\bR\tisPremium\x12%\n" +
	"\x0eexecution_mode\x18\v \x01(\tR\rexecutionMode\"\xc6\x04\n" +
	"\x0eScenarioDetail\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12%\n" +
	"\x0edescription_md\x18\x05 \x01(\tR\rdescriptionMd\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\rR\n" +
	"difficulty\x12+\n" +
	"\x11estimated_minutes\x18\b \x01(\rR\x10estimatedMinutes\x12'\n" +
	"\x0ftarget_personas\x18\t \x03(\tR\x0etargetPersonas\x12)\n" +
	"\x10experience_level\x18\n" +
	" \x01(\tR\x0fexperienceLevel\x12\x1d\n" +
	"\n" +
	"tech_stack\x18\v \x03(\tR\ttechStack\x12\x16\n" +
	"\x06skills\x18\f \x03(\tR\x06skills\x12\x1a\n" +
	"\bcommands\x18\r \x03(\tR\bcommands\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12&\n" +
	"\x05hints\x18\x0f \x03(\v2\x10.opslabs.v1.HintR\x05hints\x12\x1d\n" +
	"\n" +
	"is_premium\x18\x10 \x01(\bR\tisPremium\x12%\n" +
	"\x0eexecution_mode\x18\x11 \x01(\tR\rexecutionMode\x12\x1d\n" +
	"\n" +
	"bundle_url\x18\x12 \x01(\tR\tbundleUrl\"\x92\x01\n" +
	"\x14ListScenariosRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\rR\n" +
	"difficulty\x12\x18\n" +
	"\apersona\x18\x03 \x01(\tR\apersona\x12\x12\n" +
	"\x04tech\x18\x04 \x01(\tR\x04tech\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\"c\n" +
	"\x12ListScenariosReply\x127\n" +
	"\tscenarios\x18\x01 \x03(\v2\x19.opslabs.v1.ScenarioBriefR\tscenarios\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"(\n" +
	"\x12GetScenarioRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"G\n" +
	"\rScenarioReply\x126\n" +
	"\bscenario\x18\x01 \x01(\v2\x1a.opslabs.v1.ScenarioDetailR\bscenario\"*\n" +
	"\x14StartScenarioRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xbb\x01\n" +
	"\x12StartScenarioReply\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12!\n" +
	"\fterminal_url\x18\x02 \x01(\tR\vterminalUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12%\n" +
	"\x0eexecution_mode\x18\x04 \x01(\tR\rexecutionMode\x12\x1d\n" +
	"\n" +
	"bundle_url\x18\x05 \x01(\tR\tbundleUrl\"#\n" +
	"\x11GetAttemptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x02\n" +
	"\fAttemptReply\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12#\n" +
	"\rscenario_slug\x18\x02 \x01(\tR\fscenarioSlug\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fterminal_url\x18\x04 \x01(\tR\vterminalUrl\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12$\n" +
	"\x0elast_active_at\x18\x06 \x01(\tR\flastActiveAt\x12%\n" +
	"\x0eexecution_mode\x18\a \x01(\tR\rexecutionMode\x12\x1d\n" +
	"\n" +
	"bundle_url\x18\b \x01(\tR\tbundleUrl\"x\n" +
	"\x11ClientCheckResult\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\"i\n" +
	"\x13CheckAttemptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12B\n" +
	"\rclient_result\x18\x02 \x01(\v2\x1d.opslabs.v1.ClientCheckResultR\fclientResult\"\x91\x01\n" +
	"\x11CheckAttemptReply\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\rR\x0fdurationSeconds\x12\x1f\n" +
	"\vcheck_count\x18\x04 \x01(\rR\n" +
	"checkCount\")\n" +
	"\x17TerminateAttemptRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x15TerminateAttemptReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xdc\x01\n" +
	"\bScenario\x12h\n" +
	"\rListScenarios\x12 .opslabs.v1.ListScenariosRequest\x1a\x1e.opslabs.v1.ListScenariosReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/scenarios\x12f\n" +
	"\vGetScenario\x12\x1e.opslabs.v1.GetScenarioRequest\x1a\x19.opslabs.v1.ScenarioReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/scenarios/{slug}2\xde\x03\n" +
	"\aAttempt\x12x\n" +
	"\rStartScenario\x12 .opslabs.v1.StartScenarioRequest\x1a\x1e.opslabs.v1.StartScenarioReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/scenarios/{slug}/start\x12`\n" +
	"\n" +
	"GetAttempt\x12\x1d.opslabs.v1.GetAttemptRequest\x1a\x18.opslabs.v1.AttemptReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/attempts/{id}\x12r\n" +
	"\fCheckAttempt\x12\x1f.opslabs.v1.CheckAttemptRequest\x1a\x1d.opslabs.v1.CheckAttemptReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/attempts/{id}/check\x12\x82\x01\n" +
	"\x10TerminateAttempt\x12#.opslabs.v1.TerminateAttemptRequest\x1a!.opslabs.v1.TerminateAttemptReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/attempts/{id}/terminateBY\n" +
	"\x19dev.kratos.api.opslabs.v1B\fOpslabsProtoP\x01Z,github.com/7as0nch/backend/api/opslabs/v1;v1b\x06proto3"

var (
	file_api_opslabs_v1_opslabs_proto_rawDescOnce sync.Once
	file_api_opslabs_v1_opslabs_proto_rawDescData []byte
)

func file_api_opslabs_v1_opslabs_proto_rawDescGZIP() []byte {
	file_api_opslabs_v1_opslabs_proto_rawDescOnce.Do(func() {
		file_api_opslabs_v1_opslabs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_opslabs_v1_opslabs_proto_rawDesc), len(file_api_opslabs_v1_opslabs_proto_rawDesc)))
	})
	return file_api_opslabs_v1_opslabs_proto_rawDescData
}

var file_api_opslabs_v1_opslabs_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_opslabs_v1_opslabs_proto_goTypes = []any{
	(*Hint)(nil),                    // 0: opslabs.v1.Hint
	(*ScenarioBrief)(nil),           // 1: opslabs.v1.ScenarioBrief
	(*ScenarioDetail)(nil),          // 2: opslabs.v1.ScenarioDetail
	(*ListScenariosRequest)(nil),    // 3: opslabs.v1.ListScenariosRequest
	(*ListScenariosReply)(nil),      // 4: opslabs.v1.ListScenariosReply
	(*GetScenarioRequest)(nil),      // 5: opslabs.v1.GetScenarioRequest
	(*ScenarioReply)(nil),           // 6: opslabs.v1.ScenarioReply
	(*StartScenarioRequest)(nil),    // 7: opslabs.v1.StartScenarioRequest
	(*StartScenarioReply)(nil),      // 8: opslabs.v1.StartScenarioReply
	(*GetAttemptRequest)(nil),       // 9: opslabs.v1.GetAttemptRequest
	(*AttemptReply)(nil),            // 10: opslabs.v1.AttemptReply
	(*ClientCheckResult)(nil),       // 11: opslabs.v1.ClientCheckResult
	(*CheckAttemptRequest)(nil),     // 12: opslabs.v1.CheckAttemptRequest
	(*CheckAttemptReply)(nil),       // 13: opslabs.v1.CheckAttemptReply
	(*TerminateAttemptRequest)(nil), // 14: opslabs.v1.TerminateAttemptRequest
	(*TerminateAttemptReply)(nil),   // 15: opslabs.v1.TerminateAttemptReply
}
var file_api_opslabs_v1_opslabs_proto_depIdxs = []int32{
	0,  // 0: opslabs.v1.ScenarioDetail.hints:type_name -> opslabs.v1.Hint
	1,  // 1: opslabs.v1.ListScenariosReply.scenarios:type_name -> opslabs.v1.ScenarioBrief
	2,  // 2: opslabs.v1.ScenarioReply.scenario:type_name -> opslabs.v1.ScenarioDetail
	11, // 3: opslabs.v1.CheckAttemptRequest.client_result:type_name -> opslabs.v1.ClientCheckResult
	3,  // 4: opslabs.v1.Scenario.ListScenarios:input_type -> opslabs.v1.ListScenariosRequest
	5,  // 5: opslabs.v1.Scenario.GetScenario:input_type -> opslabs.v1.GetScenarioRequest
	7,  // 6: opslabs.v1.Attempt.StartScenario:input_type -> opslabs.v1.StartScenarioRequest
	9,  // 7: opslabs.v1.Attempt.GetAttempt:input_type -> opslabs.v1.GetAttemptRequest
	12, // 8: opslabs.v1.Attempt.CheckAttempt:input_type -> opslabs.v1.CheckAttemptRequest
	14, // 9: opslabs.v1.Attempt.TerminateAttempt:input_type -> opslabs.v1.TerminateAttemptRequest
	4,  // 10: opslabs.v1.Scenario.ListScenarios:output_type -> opslabs.v1.ListScenariosReply
	6,  // 11: opslabs.v1.Scenario.GetScenario:output_type -> opslabs.v1.ScenarioReply
	8,  // 12: opslabs.v1.Attempt.StartScenario:output_type -> opslabs.v1.StartScenarioReply
	10, // 13: opslabs.v1.Attempt.GetAttempt:output_type -> opslabs.v1.AttemptReply
	13, // 14: opslabs.v1.Attempt.CheckAttempt:output_type -> opslabs.v1.CheckAttemptReply
	15, // 15: opslabs.v1.Attempt.TerminateAttempt:output_type -> opslabs.v1.TerminateAttemptReply
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_opslabs_v1_opslabs_proto_init() }
func file_api_opslabs_v1_opslabs_proto_init() {
	if File_api_opslabs_v1_opslabs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_opslabs_v1_opslabs_proto_rawDesc), len(file_api_opslabs_v1_opslabs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_opslabs_v1_opslabs_proto_goTypes,
		DependencyIndexes: file_api_opslabs_v1_opslabs_proto_depIdxs,
		MessageInfos:      file_api_opslabs_v1_opslabs_proto_msgTypes,
	}.Build()
	File_api_opslabs_v1_opslabs_proto = out.File
	file_api_opslabs_v1_opslabs_proto_goTypes = nil
	file_api_opslabs_v1_opslabs_proto_depIdxs = nil
}
