// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.6
// source: api/opslabs/v1/opslabs.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationScenarioGetScenario = "/opslabs.v1.Scenario/GetScenario"
const OperationScenarioListScenarios = "/opslabs.v1.Scenario/ListScenarios"

type ScenarioHTTPServer interface {
	// GetScenario 场景详情(含 Markdown 描述与提示外壳)
	GetScenario(context.Context, *GetScenarioRequest) (*ScenarioReply, error)
	// ListScenarios 场景列表(支持 category / difficulty / persona 过滤,Week 1 查询参数先不生效)
	ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosReply, error)
}

func RegisterScenarioHTTPServer(s *http.Server, srv ScenarioHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/scenarios", _Scenario_ListScenarios0_HTTP_Handler(srv))
	r.GET("/v1/scenarios/{slug}", _Scenario_GetScenario0_HTTP_Handler(srv))
}

func _Scenario_ListScenarios0_HTTP_Handler(srv ScenarioHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListScenariosRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScenarioListScenarios)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListScenarios(ctx, req.(*ListScenariosRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListScenariosReply)
		return ctx.Result(200, reply)
	}
}

func _Scenario_GetScenario0_HTTP_Handler(srv ScenarioHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetScenarioRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScenarioGetScenario)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetScenario(ctx, req.(*GetScenarioRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScenarioReply)
		return ctx.Result(200, reply)
	}
}

type ScenarioHTTPClient interface {
	// GetScenario 场景详情(含 Markdown 描述与提示外壳)
	GetScenario(ctx context.Context, req *GetScenarioRequest, opts ...http.CallOption) (rsp *ScenarioReply, err error)
	// ListScenarios 场景列表(支持 category / difficulty / persona 过滤,Week 1 查询参数先不生效)
	ListScenarios(ctx context.Context, req *ListScenariosRequest, opts ...http.CallOption) (rsp *ListScenariosReply, err error)
}

type ScenarioHTTPClientImpl struct {
	cc *http.Client
}

func NewScenarioHTTPClient(client *http.Client) ScenarioHTTPClient {
	return &ScenarioHTTPClientImpl{client}
}

// GetScenario 场景详情(含 Markdown 描述与提示外壳)
func (c *ScenarioHTTPClientImpl) GetScenario(ctx context.Context, in *GetScenarioRequest, opts ...http.CallOption) (*ScenarioReply, error) {
	var out ScenarioReply
	pattern := "/v1/scenarios/{slug}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScenarioGetScenario))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListScenarios 场景列表(支持 category / difficulty / persona 过滤,Week 1 查询参数先不生效)
func (c *ScenarioHTTPClientImpl) ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...http.CallOption) (*ListScenariosReply, error) {
	var out ListScenariosReply
	pattern := "/v1/scenarios"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScenarioListScenarios))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationAttemptCheckAttempt = "/opslabs.v1.Attempt/CheckAttempt"
const OperationAttemptGetAttempt = "/opslabs.v1.Attempt/GetAttempt"
const OperationAttemptStartScenario = "/opslabs.v1.Attempt/StartScenario"
const OperationAttemptTerminateAttempt = "/opslabs.v1.Attempt/TerminateAttempt"

type AttemptHTTPServer interface {
	// CheckAttempt 判题(同步执行容器内 check.sh)
	CheckAttempt(context.Context, *CheckAttemptRequest) (*CheckAttemptReply, error)
	// GetAttempt 查询 Attempt 状态(前端每 10s 轮询,顺便更新 last_active_at)
	GetAttempt(context.Context, *GetAttemptRequest) (*AttemptReply, error)
	// StartScenario 启动场景,分配容器与 ttyd 端口
	StartScenario(context.Context, *StartScenarioRequest) (*StartScenarioReply, error)
	// TerminateAttempt 手动结束场景
	TerminateAttempt(context.Context, *TerminateAttemptRequest) (*TerminateAttemptReply, error)
}

func RegisterAttemptHTTPServer(s *http.Server, srv AttemptHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/scenarios/{slug}/start", _Attempt_StartScenario0_HTTP_Handler(srv))
	r.GET("/v1/attempts/{id}", _Attempt_GetAttempt0_HTTP_Handler(srv))
	r.POST("/v1/attempts/{id}/check", _Attempt_CheckAttempt0_HTTP_Handler(srv))
	r.POST("/v1/attempts/{id}/terminate", _Attempt_TerminateAttempt0_HTTP_Handler(srv))
}

func _Attempt_StartScenario0_HTTP_Handler(srv AttemptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartScenarioRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAttemptStartScenario)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartScenario(ctx, req.(*StartScenarioRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartScenarioReply)
		return ctx.Result(200, reply)
	}
}

func _Attempt_GetAttempt0_HTTP_Handler(srv AttemptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAttemptRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAttemptGetAttempt)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAttempt(ctx, req.(*GetAttemptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AttemptReply)
		return ctx.Result(200, reply)
	}
}

func _Attempt_CheckAttempt0_HTTP_Handler(srv AttemptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckAttemptRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAttemptCheckAttempt)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckAttempt(ctx, req.(*CheckAttemptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckAttemptReply)
		return ctx.Result(200, reply)
	}
}

func _Attempt_TerminateAttempt0_HTTP_Handler(srv AttemptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TerminateAttemptRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAttemptTerminateAttempt)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TerminateAttempt(ctx, req.(*TerminateAttemptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TerminateAttemptReply)
		return ctx.Result(200, reply)
	}
}

type AttemptHTTPClient interface {
	// CheckAttempt 判题(同步执行容器内 check.sh)
	CheckAttempt(ctx context.Context, req *CheckAttemptRequest, opts ...http.CallOption) (rsp *CheckAttemptReply, err error)
	// GetAttempt 查询 Attempt 状态(前端每 10s 轮询,顺便更新 last_active_at)
	GetAttempt(ctx context.Context, req *GetAttemptRequest, opts ...http.CallOption) (rsp *AttemptReply, err error)
	// StartScenario 启动场景,分配容器与 ttyd 端口
	StartScenario(ctx context.Context, req *StartScenarioRequest, opts ...http.CallOption) (rsp *StartScenarioReply, err error)
	// TerminateAttempt 手动结束场景
	TerminateAttempt(ctx context.Context, req *TerminateAttemptRequest, opts ...http.CallOption) (rsp *TerminateAttemptReply, err error)
}

type AttemptHTTPClientImpl struct {
	cc *http.Client
}

func NewAttemptHTTPClient(client *http.Client) AttemptHTTPClient {
	return &AttemptHTTPClientImpl{client}
}

// CheckAttempt 判题(同步执行容器内 check.sh)
func (c *AttemptHTTPClientImpl) CheckAttempt(ctx context.Context, in *CheckAttemptRequest, opts ...http.CallOption) (*CheckAttemptReply, error) {
	var out CheckAttemptReply
	pattern := "/v1/attempts/{id}/check"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAttemptCheckAttempt))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAttempt 查询 Attempt 状态(前端每 10s 轮询,顺便更新 last_active_at)
func (c *AttemptHTTPClientImpl) GetAttempt(ctx context.Context, in *GetAttemptRequest, opts ...http.CallOption) (*AttemptReply, error) {
	var out AttemptReply
	pattern := "/v1/attempts/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAttemptGetAttempt))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartScenario 启动场景,分配容器与 ttyd 端口
func (c *AttemptHTTPClientImpl) StartScenario(ctx context.Context, in *StartScenarioRequest, opts ...http.CallOption) (*StartScenarioReply, error) {
	var out StartScenarioReply
	pattern := "/v1/scenarios/{slug}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAttemptStartScenario))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TerminateAttempt 手动结束场景
func (c *AttemptHTTPClientImpl) TerminateAttempt(ctx context.Context, in *TerminateAttemptRequest, opts ...http.CallOption) (*TerminateAttemptReply, error) {
	var out TerminateAttemptReply
	pattern := "/v1/attempts/{id}/terminate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAttemptTerminateAttempt))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
