// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: api/opslabs/v1/opslabs.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scenario_ListScenarios_FullMethodName = "/opslabs.v1.Scenario/ListScenarios"
	Scenario_GetScenario_FullMethodName   = "/opslabs.v1.Scenario/GetScenario"
)

// ScenarioClient is the client API for Scenario service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =====================================================================
// Scenario 场景元信息服务
// =====================================================================
type ScenarioClient interface {
	// 场景列表(支持 category / difficulty / persona 过滤,Week 1 查询参数先不生效)
	ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosReply, error)
	// 场景详情(含 Markdown 描述与提示外壳)
	GetScenario(ctx context.Context, in *GetScenarioRequest, opts ...grpc.CallOption) (*ScenarioReply, error)
}

type scenarioClient struct {
	cc grpc.ClientConnInterface
}

func NewScenarioClient(cc grpc.ClientConnInterface) ScenarioClient {
	return &scenarioClient{cc}
}

func (c *scenarioClient) ListScenarios(ctx context.Context, in *ListScenariosRequest, opts ...grpc.CallOption) (*ListScenariosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScenariosReply)
	err := c.cc.Invoke(ctx, Scenario_ListScenarios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenarioClient) GetScenario(ctx context.Context, in *GetScenarioRequest, opts ...grpc.CallOption) (*ScenarioReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScenarioReply)
	err := c.cc.Invoke(ctx, Scenario_GetScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScenarioServer is the server API for Scenario service.
// All implementations must embed UnimplementedScenarioServer
// for forward compatibility.
//
// =====================================================================
// Scenario 场景元信息服务
// =====================================================================
type ScenarioServer interface {
	// 场景列表(支持 category / difficulty / persona 过滤,Week 1 查询参数先不生效)
	ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosReply, error)
	// 场景详情(含 Markdown 描述与提示外壳)
	GetScenario(context.Context, *GetScenarioRequest) (*ScenarioReply, error)
	mustEmbedUnimplementedScenarioServer()
}

// UnimplementedScenarioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScenarioServer struct{}

func (UnimplementedScenarioServer) ListScenarios(context.Context, *ListScenariosRequest) (*ListScenariosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScenarios not implemented")
}
func (UnimplementedScenarioServer) GetScenario(context.Context, *GetScenarioRequest) (*ScenarioReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScenario not implemented")
}
func (UnimplementedScenarioServer) mustEmbedUnimplementedScenarioServer() {}
func (UnimplementedScenarioServer) testEmbeddedByValue()                  {}

// UnsafeScenarioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScenarioServer will
// result in compilation errors.
type UnsafeScenarioServer interface {
	mustEmbedUnimplementedScenarioServer()
}

func RegisterScenarioServer(s grpc.ServiceRegistrar, srv ScenarioServer) {
	// If the following call panics, it indicates UnimplementedScenarioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scenario_ServiceDesc, srv)
}

func _Scenario_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenariosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scenario_ListScenarios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServer).ListScenarios(ctx, req.(*ListScenariosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scenario_GetScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenarioServer).GetScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scenario_GetScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenarioServer).GetScenario(ctx, req.(*GetScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scenario_ServiceDesc is the grpc.ServiceDesc for Scenario service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scenario_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opslabs.v1.Scenario",
	HandlerType: (*ScenarioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListScenarios",
			Handler:    _Scenario_ListScenarios_Handler,
		},
		{
			MethodName: "GetScenario",
			Handler:    _Scenario_GetScenario_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/opslabs/v1/opslabs.proto",
}

const (
	Attempt_StartScenario_FullMethodName    = "/opslabs.v1.Attempt/StartScenario"
	Attempt_GetAttempt_FullMethodName       = "/opslabs.v1.Attempt/GetAttempt"
	Attempt_CheckAttempt_FullMethodName     = "/opslabs.v1.Attempt/CheckAttempt"
	Attempt_TerminateAttempt_FullMethodName = "/opslabs.v1.Attempt/TerminateAttempt"
)

// AttemptClient is the client API for Attempt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =====================================================================
// Attempt 场景尝试服务
// =====================================================================
type AttemptClient interface {
	// 启动场景,分配容器与 ttyd 端口
	StartScenario(ctx context.Context, in *StartScenarioRequest, opts ...grpc.CallOption) (*StartScenarioReply, error)
	// 查询 Attempt 状态(前端每 10s 轮询,顺便更新 last_active_at)
	GetAttempt(ctx context.Context, in *GetAttemptRequest, opts ...grpc.CallOption) (*AttemptReply, error)
	// 判题(同步执行容器内 check.sh)
	CheckAttempt(ctx context.Context, in *CheckAttemptRequest, opts ...grpc.CallOption) (*CheckAttemptReply, error)
	// 手动结束场景
	TerminateAttempt(ctx context.Context, in *TerminateAttemptRequest, opts ...grpc.CallOption) (*TerminateAttemptReply, error)
}

type attemptClient struct {
	cc grpc.ClientConnInterface
}

func NewAttemptClient(cc grpc.ClientConnInterface) AttemptClient {
	return &attemptClient{cc}
}

func (c *attemptClient) StartScenario(ctx context.Context, in *StartScenarioRequest, opts ...grpc.CallOption) (*StartScenarioReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartScenarioReply)
	err := c.cc.Invoke(ctx, Attempt_StartScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attemptClient) GetAttempt(ctx context.Context, in *GetAttemptRequest, opts ...grpc.CallOption) (*AttemptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttemptReply)
	err := c.cc.Invoke(ctx, Attempt_GetAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attemptClient) CheckAttempt(ctx context.Context, in *CheckAttemptRequest, opts ...grpc.CallOption) (*CheckAttemptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAttemptReply)
	err := c.cc.Invoke(ctx, Attempt_CheckAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attemptClient) TerminateAttempt(ctx context.Context, in *TerminateAttemptRequest, opts ...grpc.CallOption) (*TerminateAttemptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateAttemptReply)
	err := c.cc.Invoke(ctx, Attempt_TerminateAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttemptServer is the server API for Attempt service.
// All implementations must embed UnimplementedAttemptServer
// for forward compatibility.
//
// =====================================================================
// Attempt 场景尝试服务
// =====================================================================
type AttemptServer interface {
	// 启动场景,分配容器与 ttyd 端口
	StartScenario(context.Context, *StartScenarioRequest) (*StartScenarioReply, error)
	// 查询 Attempt 状态(前端每 10s 轮询,顺便更新 last_active_at)
	GetAttempt(context.Context, *GetAttemptRequest) (*AttemptReply, error)
	// 判题(同步执行容器内 check.sh)
	CheckAttempt(context.Context, *CheckAttemptRequest) (*CheckAttemptReply, error)
	// 手动结束场景
	TerminateAttempt(context.Context, *TerminateAttemptRequest) (*TerminateAttemptReply, error)
	mustEmbedUnimplementedAttemptServer()
}

// UnimplementedAttemptServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttemptServer struct{}

func (UnimplementedAttemptServer) StartScenario(context.Context, *StartScenarioRequest) (*StartScenarioReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StartScenario not implemented")
}
func (UnimplementedAttemptServer) GetAttempt(context.Context, *GetAttemptRequest) (*AttemptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttempt not implemented")
}
func (UnimplementedAttemptServer) CheckAttempt(context.Context, *CheckAttemptRequest) (*CheckAttemptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAttempt not implemented")
}
func (UnimplementedAttemptServer) TerminateAttempt(context.Context, *TerminateAttemptRequest) (*TerminateAttemptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateAttempt not implemented")
}
func (UnimplementedAttemptServer) mustEmbedUnimplementedAttemptServer() {}
func (UnimplementedAttemptServer) testEmbeddedByValue()                 {}

// UnsafeAttemptServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttemptServer will
// result in compilation errors.
type UnsafeAttemptServer interface {
	mustEmbedUnimplementedAttemptServer()
}

func RegisterAttemptServer(s grpc.ServiceRegistrar, srv AttemptServer) {
	// If the following call panics, it indicates UnimplementedAttemptServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Attempt_ServiceDesc, srv)
}

func _Attempt_StartScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttemptServer).StartScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Attempt_StartScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttemptServer).StartScenario(ctx, req.(*StartScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Attempt_GetAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttemptServer).GetAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Attempt_GetAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttemptServer).GetAttempt(ctx, req.(*GetAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Attempt_CheckAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttemptServer).CheckAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Attempt_CheckAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttemptServer).CheckAttempt(ctx, req.(*CheckAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Attempt_TerminateAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttemptServer).TerminateAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Attempt_TerminateAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttemptServer).TerminateAttempt(ctx, req.(*TerminateAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Attempt_ServiceDesc is the grpc.ServiceDesc for Attempt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Attempt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opslabs.v1.Attempt",
	HandlerType: (*AttemptServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScenario",
			Handler:    _Attempt_StartScenario_Handler,
		},
		{
			MethodName: "GetAttempt",
			Handler:    _Attempt_GetAttempt_Handler,
		},
		{
			MethodName: "CheckAttempt",
			Handler:    _Attempt_CheckAttempt_Handler,
		},
		{
			MethodName: "TerminateAttempt",
			Handler:    _Attempt_TerminateAttempt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/opslabs/v1/opslabs.proto",
}
