// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/7as0nch/backend/internal/biz/attempt"
	"github.com/7as0nch/backend/internal/biz/base"
	"github.com/7as0nch/backend/internal/biz/base/loginprovider"
	"github.com/7as0nch/backend/internal/conf"
	"github.com/7as0nch/backend/internal/data"
	"github.com/7as0nch/backend/internal/db"
	"github.com/7as0nch/backend/internal/server"
	base2 "github.com/7as0nch/backend/internal/service/base"
	"github.com/7as0nch/backend/internal/service/opslabs"
	"github.com/7as0nch/backend/pkg/auth"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.uber.org/zap"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, bootstrap *conf.Bootstrap, logger *zap.Logger, logLogger log.Logger) (*kratos.App, func(), error) {
	dataRepo, cleanup, err := db.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	sysUserRepo := data.NewSysUserRepo(dataRepo)
	authRepo := auth.NewAuthRepo()
	redisRepo := db.NewRedisRepo(dataRepo)
	stateCache := loginprovider.NewStateCache(redisRepo)
	sysUserUseCase := base.NewSysUserUseCase(sysUserRepo, authRepo, stateCache, bootstrap)
	authService := base2.NewAuthService(sysUserUseCase)
	sysMenuRepo := data.NewSysMenuRepo(dataRepo, logger)
	sysMenuUseCase := base.NewSysMenuUseCase(sysMenuRepo)
	dictTypeRepo := data.NewDictTypeRepo(dataRepo, logger)
	dictDataRepo := data.NewDictDataRepo(dataRepo, logger)
	transaction := data.NewTransaction(dataRepo)
	dictTypeUseCase := base.NewDictTypeUseCase(dictTypeRepo, dictDataRepo, transaction)
	dictDataUseCase := base.NewDictDataUseCase(dictDataRepo)
	systemService := base2.NewSystemService(sysMenuUseCase, dictTypeUseCase, dictDataUseCase)
	trackerRepo := data.NewTrackerRepo(dataRepo, logger)
	trackerUseCase := base.NewTrackerUseCase(trackerRepo)
	trackerService := base2.NewTrackerService(trackerUseCase)
	registry := server.NewScenarioRegistry()
	scenarioService := opslabs.NewScenarioService(registry)
	attemptRepo := data.NewAttemptRepo(dataRepo, logger)
	attemptStore := server.NewAttemptStore(redisRepo, logger)
	runner := server.NewRunner(bootstrap, logger)
	attemptUsecase := attempt.NewAttemptUsecase(attemptRepo, attemptStore, runner, registry, logger)
	serviceOptions := server.NewOpslabsServiceOptions(bootstrap)
	attemptService := opslabs.NewAttemptService(attemptUsecase, serviceOptions, registry)
	grpcServer := server.NewGRPCServer(confServer, authService, systemService, trackerService, scenarioService, attemptService, logLogger)
	httpServer := server.NewHTTPServer(confServer, authService, authRepo, systemService, trackerService, scenarioService, attemptService, attemptStore, logger, logLogger)
	webSocketServer := server.NewWebSocketServer(logger)
	webSocketApp := server.NewWebSocketApp(webSocketServer, logger)
	gcServer := server.NewGCServer(attemptStore, attemptUsecase, runner, bootstrap, logger)
	app := newApp(logLogger, grpcServer, httpServer, webSocketApp, gcServer)
	return app, func() {
		cleanup()
	}, nil
}
