// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/base/auth.proto

package base

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,4,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Sex           string                 `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_base_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *RegisterRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type UpdatePwdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePwdRequest) Reset() {
	*x = UpdatePwdRequest{}
	mi := &file_api_base_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePwdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePwdRequest) ProtoMessage() {}

func (x *UpdatePwdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePwdRequest.ProtoReflect.Descriptor instead.
func (*UpdatePwdRequest) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePwdRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePwdRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type GetInfoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoReply) Reset() {
	*x = GetInfoReply{}
	mi := &file_api_base_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoReply) ProtoMessage() {}

func (x *GetInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoReply.ProtoReflect.Descriptor instead.
func (*GetInfoReply) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetInfoReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetInfoReply) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetInfoReply) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	LoginType     string                 `protobuf:"bytes,3,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"` // "password", "phone", "qq"
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`                         // 手机验证码
	AuthCode      string                 `protobuf:"bytes,6,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"` // 第三方登录授权码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_base_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetLoginType() string {
	if x != nil {
		return x.LoginType
	}
	return ""
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginRequest) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_base_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_base_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{5}
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataScope     string                 `protobuf:"bytes,1,opt,name=data_scope,json=dataScope,proto3" json:"data_scope,omitempty"`
	Flag          bool                   `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleKey       string                 `protobuf:"bytes,4,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	RoleName      string                 `protobuf:"bytes,5,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleSort      int32                  `protobuf:"varint,6,opt,name=role_sort,json=roleSort,proto3" json:"role_sort,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	SuperAdmin    bool                   `protobuf:"varint,8,opt,name=super_admin,json=superAdmin,proto3" json:"super_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_api_base_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{6}
}

func (x *Role) GetDataScope() string {
	if x != nil {
		return x.DataScope
	}
	return ""
}

func (x *Role) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *Role) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *Role) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *Role) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *Role) GetRoleSort() int32 {
	if x != nil {
		return x.RoleSort
	}
	return 0
}

func (x *Role) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Role) GetSuperAdmin() bool {
	if x != nil {
		return x.SuperAdmin
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreateTime    string                 `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	DeptId        int64                  `protobuf:"varint,3,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	DeptName      string                 `protobuf:"bytes,4,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	LoginDate     string                 `protobuf:"bytes,6,opt,name=login_date,json=loginDate,proto3" json:"login_date,omitempty"`
	LoginIp       string                 `protobuf:"bytes,7,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`
	NickName      string                 `protobuf:"bytes,8,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,9,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	Roles         []*Role                `protobuf:"bytes,11,rep,name=roles,proto3" json:"roles,omitempty"`
	Sex           string                 `protobuf:"bytes,12,opt,name=sex,proto3" json:"sex,omitempty"`
	Status        string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	TenantId      string                 `protobuf:"bytes,14,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        int64                  `protobuf:"varint,15,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,16,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserType      string                 `protobuf:"bytes,17,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_base_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_base_auth_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *User) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *User) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetLoginDate() string {
	if x != nil {
		return x.LoginDate
	}
	return ""
}

func (x *User) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *User) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *User) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *User) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *User) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

var File_api_base_auth_proto protoreflect.FileDescriptor

const file_api_base_auth_proto_rawDesc = "" +
	"\n" +
	"\x13api/base/auth.proto\x12\x04base\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x91\x01\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12 \n" +
	"\vphonenumber\x18\x04 \x01(\tR\vphonenumber\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\tR\x03sex\"V\n" +
	"\x10UpdatePwdRequest\x12 \n" +
	"\voldPassword\x18\x01 \x01(\tR\voldPassword\x12 \n" +
	"\vnewPassword\x18\x02 \x01(\tR\vnewPassword\"f\n" +
	"\fGetInfoReply\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".base.UserR\x04user\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"\xac\x01\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"login_type\x18\x03 \x01(\tR\tloginType\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x1b\n" +
	"\tauth_code\x18\x06 \x01(\tR\bauthCode\"E\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x0f\n" +
	"\rLogoutRequest\"\xe0\x01\n" +
	"\x04Role\x12\x1d\n" +
	"\n" +
	"data_scope\x18\x01 \x01(\tR\tdataScope\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\bR\x04flag\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId\x12\x19\n" +
	"\brole_key\x18\x04 \x01(\tR\aroleKey\x12\x1b\n" +
	"\trole_name\x18\x05 \x01(\tR\broleName\x12\x1b\n" +
	"\trole_sort\x18\x06 \x01(\x05R\broleSort\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vsuper_admin\x18\b \x01(\bR\n" +
	"superAdmin\"\xd8\x03\n" +
	"\x04User\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vcreate_time\x18\x02 \x01(\tR\n" +
	"createTime\x12\x17\n" +
	"\adept_id\x18\x03 \x01(\x03R\x06deptId\x12\x1b\n" +
	"\tdept_name\x18\x04 \x01(\tR\bdeptName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"login_date\x18\x06 \x01(\tR\tloginDate\x12\x19\n" +
	"\blogin_ip\x18\a \x01(\tR\aloginIp\x12\x1b\n" +
	"\tnick_name\x18\b \x01(\tR\bnickName\x12 \n" +
	"\vphonenumber\x18\t \x01(\tR\vphonenumber\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\x12 \n" +
	"\x05roles\x18\v \x03(\v2\n" +
	".base.RoleR\x05roles\x12\x10\n" +
	"\x03sex\x18\f \x01(\tR\x03sex\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1b\n" +
	"\ttenant_id\x18\x0e \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x0f \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x10 \x01(\tR\buserName\x12\x1b\n" +
	"\tuser_type\x18\x11 \x01(\tR\buserType2\xdb\x04\n" +
	"\x04Auth\x12E\n" +
	"\x05Login\x12\x12.base.LoginRequest\x1a\x10.base.LoginReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/auth/login\x12N\n" +
	"\aGetInfo\x12\x16.google.protobuf.Empty\x1a\x12.base.GetInfoReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/auth/user/info\x12Q\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/auth/logout\x12Y\n" +
	"\bRegister\x12\x15.base.RegisterRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/auth/user/register\x12T\n" +
	"\n" +
	"GetProfile\x12\x16.google.protobuf.Empty\x1a\x12.base.GetInfoReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/auth/user/profile\x12R\n" +
	"\rUpdateProfile\x12\n" +
	".base.User\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/auth/user/profile\x12d\n" +
	"\tUpdatePwd\x12\x16.base.UpdatePwdRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/auth/user/profile/updatePwdBN\n" +
	"\x13dev.kratos.api.baseB\tBaseProtoP\x01Z*github.com/example/aichat/backend/api;baseb\x06proto3"

var (
	file_api_base_auth_proto_rawDescOnce sync.Once
	file_api_base_auth_proto_rawDescData []byte
)

func file_api_base_auth_proto_rawDescGZIP() []byte {
	file_api_base_auth_proto_rawDescOnce.Do(func() {
		file_api_base_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_base_auth_proto_rawDesc), len(file_api_base_auth_proto_rawDesc)))
	})
	return file_api_base_auth_proto_rawDescData
}

var file_api_base_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_base_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: base.RegisterRequest
	(*UpdatePwdRequest)(nil), // 1: base.UpdatePwdRequest
	(*GetInfoReply)(nil),     // 2: base.GetInfoReply
	(*LoginRequest)(nil),     // 3: base.LoginRequest
	(*LoginReply)(nil),       // 4: base.LoginReply
	(*LogoutRequest)(nil),    // 5: base.LogoutRequest
	(*Role)(nil),             // 6: base.Role
	(*User)(nil),             // 7: base.User
	(*emptypb.Empty)(nil),    // 8: google.protobuf.Empty
}
var file_api_base_auth_proto_depIdxs = []int32{
	7, // 0: base.GetInfoReply.user:type_name -> base.User
	6, // 1: base.User.roles:type_name -> base.Role
	3, // 2: base.Auth.Login:input_type -> base.LoginRequest
	8, // 3: base.Auth.GetInfo:input_type -> google.protobuf.Empty
	8, // 4: base.Auth.Logout:input_type -> google.protobuf.Empty
	0, // 5: base.Auth.Register:input_type -> base.RegisterRequest
	8, // 6: base.Auth.GetProfile:input_type -> google.protobuf.Empty
	7, // 7: base.Auth.UpdateProfile:input_type -> base.User
	1, // 8: base.Auth.UpdatePwd:input_type -> base.UpdatePwdRequest
	4, // 9: base.Auth.Login:output_type -> base.LoginReply
	2, // 10: base.Auth.GetInfo:output_type -> base.GetInfoReply
	8, // 11: base.Auth.Logout:output_type -> google.protobuf.Empty
	8, // 12: base.Auth.Register:output_type -> google.protobuf.Empty
	2, // 13: base.Auth.GetProfile:output_type -> base.GetInfoReply
	8, // 14: base.Auth.UpdateProfile:output_type -> google.protobuf.Empty
	8, // 15: base.Auth.UpdatePwd:output_type -> google.protobuf.Empty
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_base_auth_proto_init() }
func file_api_base_auth_proto_init() {
	if File_api_base_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_base_auth_proto_rawDesc), len(file_api_base_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_auth_proto_goTypes,
		DependencyIndexes: file_api_base_auth_proto_depIdxs,
		MessageInfos:      file_api_base_auth_proto_msgTypes,
	}.Build()
	File_api_base_auth_proto = out.File
	file_api_base_auth_proto_goTypes = nil
	file_api_base_auth_proto_depIdxs = nil
}
