// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/base/beta_application.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BetaApplication_CreateApplication_FullMethodName = "/base.BetaApplication/CreateApplication"
)

// BetaApplicationClient is the client API for BetaApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BetaApplicationClient interface {
	CreateApplication(ctx context.Context, in *CreateBetaApplicationRequest, opts ...grpc.CallOption) (*CreateBetaApplicationReply, error)
}

type betaApplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewBetaApplicationClient(cc grpc.ClientConnInterface) BetaApplicationClient {
	return &betaApplicationClient{cc}
}

func (c *betaApplicationClient) CreateApplication(ctx context.Context, in *CreateBetaApplicationRequest, opts ...grpc.CallOption) (*CreateBetaApplicationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBetaApplicationReply)
	err := c.cc.Invoke(ctx, BetaApplication_CreateApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BetaApplicationServer is the server API for BetaApplication service.
// All implementations must embed UnimplementedBetaApplicationServer
// for forward compatibility.
type BetaApplicationServer interface {
	CreateApplication(context.Context, *CreateBetaApplicationRequest) (*CreateBetaApplicationReply, error)
	mustEmbedUnimplementedBetaApplicationServer()
}

// UnimplementedBetaApplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBetaApplicationServer struct{}

func (UnimplementedBetaApplicationServer) CreateApplication(context.Context, *CreateBetaApplicationRequest) (*CreateBetaApplicationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplication not implemented")
}
func (UnimplementedBetaApplicationServer) mustEmbedUnimplementedBetaApplicationServer() {}
func (UnimplementedBetaApplicationServer) testEmbeddedByValue()                         {}

// UnsafeBetaApplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BetaApplicationServer will
// result in compilation errors.
type UnsafeBetaApplicationServer interface {
	mustEmbedUnimplementedBetaApplicationServer()
}

func RegisterBetaApplicationServer(s grpc.ServiceRegistrar, srv BetaApplicationServer) {
	// If the following call pancis, it indicates UnimplementedBetaApplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BetaApplication_ServiceDesc, srv)
}

func _BetaApplication_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBetaApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetaApplicationServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BetaApplication_CreateApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetaApplicationServer).CreateApplication(ctx, req.(*CreateBetaApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BetaApplication_ServiceDesc is the grpc.ServiceDesc for BetaApplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BetaApplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base.BetaApplication",
	HandlerType: (*BetaApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApplication",
			Handler:    _BetaApplication_CreateApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/base/beta_application.proto",
}
