// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: api/base/beta_application.proto

package base

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBetaApplicationCreateApplication = "/base.BetaApplication/CreateApplication"

type BetaApplicationHTTPServer interface {
	CreateApplication(context.Context, *CreateBetaApplicationRequest) (*CreateBetaApplicationReply, error)
}

func RegisterBetaApplicationHTTPServer(s *http.Server, srv BetaApplicationHTTPServer) {
	r := s.Route("/")
	r.POST("/beta/applications", _BetaApplication_CreateApplication0_HTTP_Handler(srv))
}

func _BetaApplication_CreateApplication0_HTTP_Handler(srv BetaApplicationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateBetaApplicationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBetaApplicationCreateApplication)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateApplication(ctx, req.(*CreateBetaApplicationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateBetaApplicationReply)
		return ctx.Result(200, reply)
	}
}

type BetaApplicationHTTPClient interface {
	CreateApplication(ctx context.Context, req *CreateBetaApplicationRequest, opts ...http.CallOption) (rsp *CreateBetaApplicationReply, err error)
}

type BetaApplicationHTTPClientImpl struct {
	cc *http.Client
}

func NewBetaApplicationHTTPClient(client *http.Client) BetaApplicationHTTPClient {
	return &BetaApplicationHTTPClientImpl{client}
}

func (c *BetaApplicationHTTPClientImpl) CreateApplication(ctx context.Context, in *CreateBetaApplicationRequest, opts ...http.CallOption) (*CreateBetaApplicationReply, error) {
	var out CreateBetaApplicationReply
	pattern := "/beta/applications"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBetaApplicationCreateApplication))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
