// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: base/tracker.proto

package base

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tracker 埋点数据消息
type TrackerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 应用ID
	AppId string `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	// 设备ID
	DeviceId string `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// 用户ID
	UserId int64 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	// 时间戳
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 用户代理
	UserAgent string `protobuf:"bytes,5,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	// 页面URL
	PageUrl string `protobuf:"bytes,6,opt,name=pageUrl,proto3" json:"pageUrl,omitempty"`
	// 类型
	Type string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	// 数据
	Data          string `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackerMessage) Reset() {
	*x = TrackerMessage{}
	mi := &file_base_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerMessage) ProtoMessage() {}

func (x *TrackerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_base_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerMessage.ProtoReflect.Descriptor instead.
func (*TrackerMessage) Descriptor() ([]byte, []int) {
	return file_base_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *TrackerMessage) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *TrackerMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TrackerMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrackerMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *TrackerMessage) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *TrackerMessage) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *TrackerMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TrackerMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// BatchRequest 批量新增请求
type BatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 埋点数据列表
	Logs          []*TrackerMessage `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_base_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_base_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *BatchRequest) GetLogs() []*TrackerMessage {
	if x != nil {
		return x.Logs
	}
	return nil
}

// BatchReply 批量新增响应
type BatchReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 成功数量
	SuccessCount int32 `protobuf:"varint,1,opt,name=successCount,proto3" json:"successCount,omitempty"`
	// 失败数量
	FailedCount   int32 `protobuf:"varint,2,opt,name=failedCount,proto3" json:"failedCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchReply) Reset() {
	*x = BatchReply{}
	mi := &file_base_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReply) ProtoMessage() {}

func (x *BatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_base_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReply.ProtoReflect.Descriptor instead.
func (*BatchReply) Descriptor() ([]byte, []int) {
	return file_base_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *BatchReply) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchReply) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

// ListRequest 分页查询请求
type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码
	PageNum int32 `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 每页数量
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// 应用ID
	AppId string `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId,omitempty"`
	// 设备ID
	DeviceId string `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// 用户ID
	UserId int64 `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	// 类型
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// 页面URL
	PageUrl string `protobuf:"bytes,7,opt,name=pageUrl,proto3" json:"pageUrl,omitempty"`
	// 开始时间
	StartTime string `protobuf:"bytes,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// 结束时间
	EndTime       string `protobuf:"bytes,9,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_base_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_base_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ListRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListRequest) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *ListRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ListRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// ListReply 分页查询响应
type ListReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 埋点数据列表
	List []*TrackerMessage `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 总数量
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_base_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_base_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_base_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *ListReply) GetList() []*TrackerMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_base_tracker_proto protoreflect.FileDescriptor

const file_base_tracker_proto_rawDesc = "" +
	"\n" +
	"\x12base/tracker.proto\x12\x04base\x1a\x1cgoogle/api/annotations.proto\"\xd8\x01\n" +
	"\x0eTrackerMessage\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bdeviceId\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x1c\n" +
	"\tuserAgent\x18\x05 \x01(\tR\tuserAgent\x12\x18\n" +
	"\apageUrl\x18\x06 \x01(\tR\apageUrl\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\b \x01(\tR\x04data\"8\n" +
	"\fBatchRequest\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.base.TrackerMessageR\x04logs\"R\n" +
	"\n" +
	"BatchReply\x12\"\n" +
	"\fsuccessCount\x18\x01 \x01(\x05R\fsuccessCount\x12 \n" +
	"\vfailedCount\x18\x02 \x01(\x05R\vfailedCount\"\xf3\x01\n" +
	"\vListRequest\x12\x18\n" +
	"\apageNum\x18\x01 \x01(\x05R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05appId\x18\x03 \x01(\tR\x05appId\x12\x1a\n" +
	"\bdeviceId\x18\x04 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06userId\x18\x05 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x18\n" +
	"\apageUrl\x18\a \x01(\tR\apageUrl\x12\x1c\n" +
	"\tstartTime\x18\b \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\t \x01(\tR\aendTime\"K\n" +
	"\tListReply\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.base.TrackerMessageR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x96\x01\n" +
	"\aTracker\x12H\n" +
	"\x05Batch\x12\x12.base.BatchRequest\x1a\x10.base.BatchReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/tracker/batch\x12A\n" +
	"\x04List\x12\x11.base.ListRequest\x1a\x0f.base.ListReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/tracker/listBQ\n" +
	"\x13dev.kratos.api.baseB\fTrackerProtoP\x01Z*github.com/example/aichat/backend/api;baseb\x06proto3"

var (
	file_base_tracker_proto_rawDescOnce sync.Once
	file_base_tracker_proto_rawDescData []byte
)

func file_base_tracker_proto_rawDescGZIP() []byte {
	file_base_tracker_proto_rawDescOnce.Do(func() {
		file_base_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_tracker_proto_rawDesc), len(file_base_tracker_proto_rawDesc)))
	})
	return file_base_tracker_proto_rawDescData
}

var file_base_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_base_tracker_proto_goTypes = []any{
	(*TrackerMessage)(nil), // 0: base.TrackerMessage
	(*BatchRequest)(nil),   // 1: base.BatchRequest
	(*BatchReply)(nil),     // 2: base.BatchReply
	(*ListRequest)(nil),    // 3: base.ListRequest
	(*ListReply)(nil),      // 4: base.ListReply
}
var file_base_tracker_proto_depIdxs = []int32{
	0, // 0: base.BatchRequest.logs:type_name -> base.TrackerMessage
	0, // 1: base.ListReply.list:type_name -> base.TrackerMessage
	1, // 2: base.Tracker.Batch:input_type -> base.BatchRequest
	3, // 3: base.Tracker.List:input_type -> base.ListRequest
	2, // 4: base.Tracker.Batch:output_type -> base.BatchReply
	4, // 5: base.Tracker.List:output_type -> base.ListReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_base_tracker_proto_init() }
func file_base_tracker_proto_init() {
	if File_base_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_tracker_proto_rawDesc), len(file_base_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_tracker_proto_goTypes,
		DependencyIndexes: file_base_tracker_proto_depIdxs,
		MessageInfos:      file_base_tracker_proto_msgTypes,
	}.Build()
	File_base_tracker_proto = out.File
	file_base_tracker_proto_goTypes = nil
	file_base_tracker_proto_depIdxs = nil
}
